import Link from "next/link";
import { CheckCircle2, Sparkles, TriangleAlert, Wrench } from "lucide-react";
import type { LessonPlan } from "@/data/lessonPlans";
import { NOMES_DAS_TURMAS, NOMES_DOS_NIVEIS_DE_PLANO } from "@/data/lessonPlans";
import type { GuiaTecnicoMicrobit as Guia } from "@/data/microbitTechnicalGuides";
import { buildLessonSupport } from "@/data/lessonSupport";
import { BotaoFavorito } from "@/components/support/BotaoFavorito";
import { MarcarLido } from "@/components/content/MarcarLido";
import { Button } from "@/components/ui/Button";
import { BotaoImprimir } from "./BotaoImprimir";
import { EtapasGuiadas } from "./EtapasGuiadas";
import { GuiaTecnicoMicrobit } from "./GuiaTecnicoMicrobit";
import { ProntidaoDaAula } from "./ProntidaoDaAula";

type Neighbor = { id: string; title: string };
type PathInfo = { previous: Neighbor | null; next: Neighbor | null; position: number } | null;

function Heading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <header><p className="label-mono text-cyan">{eyebrow}</p><h2 className="mt-2 font-display text-[clamp(1.7rem,3vw,2.3rem)] font-extrabold leading-tight tracking-display">{title}</h2><p className="mt-3 max-w-[70ch] text-[13.5px] leading-relaxed text-navy/68">{description}</p></header>;
}

export function AulaCompletaGuiada({ plan, guide, path, total }: { plan: LessonPlan; guide?: Guia; path: PathInfo; total: number }) {
  const firstYear = plan.ageBands[0].split("-")[0];
  const lastYear = plan.ageBands[plan.ageBands.length - 1].split("-")[1];
  const years = firstYear === lastYear ? `${firstYear}º ano` : `do ${firstYear}º ao ${lastYear}º ano`;
  const support = buildLessonSupport(plan, guide);

  const aprender = <>
    <Heading eyebrow="Etapa 1 · Aprenda" title="Entenda o conteúdo antes de explicar" description="Leia o sentido pedagógico, revise os conceitos relacionados e responda ao teste de prontidão. Não avance enquanto ainda precisar ler a definição para explicar."/>
    <section className="mt-6 grid max-w-[1050px] gap-4 lg:grid-cols-2">
      <div className="rounded-card border border-purple/20 bg-purple/8 p-5"><h3 className="font-display text-[19px] font-extrabold">Por que esta aula é importante</h3><p className="mt-3 text-[13.5px] leading-relaxed text-navy/72">{plan.whyApply ?? `Esta aula transforma ${plan.theme.toLowerCase()} em uma experiência concreta de previsão, construção, teste e correção.`}</p><p className="mt-3 border-l-2 border-purple pl-3 text-[12.5px] leading-relaxed text-navy/65"><strong>No cotidiano:</strong> {support.everyday}</p></div>
      <div className="rounded-card border border-cyan/20 bg-cyan/8 p-5"><h3 className="font-display text-[19px] font-extrabold">O que saber antes de começar</h3><p className="mt-2 text-[12.5px] leading-relaxed text-navy/65">Abra qualquer item que ainda não consiga explicar com um exemplo próprio.</p><ul className="mt-4 grid gap-2">{(plan.teacherPrerequisites ?? plan.relatedContent.slice(0, 3)).map((item) => <li key={item.href}><Link href={item.href} className="inline-flex min-h-[34px] items-center text-[13px] font-bold text-navy underline">Professor: {item.label}</Link></li>)}</ul><p className="mt-4 label-mono text-cyan">Os alunos precisam</p><ul className="mt-2 grid gap-1.5 text-[12.5px] leading-relaxed text-navy/68">{(plan.studentPrerequisites ?? ["Conseguir seguir uma sequência curta", "Registrar uma previsão antes do teste", "Nenhuma experiência técnica anterior nas aulas iniciantes"]).map((item) => <li key={item}>• {item}</li>)}</ul></div>
    </section>
    <section className="mt-7 max-w-[1050px]"><h3 className="font-display text-[20px] font-extrabold">Conceitos que o professor precisa dominar</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{support.concepts.map((concept) => <article key={concept.id} className="rounded-card-sm border border-navy/8 bg-white p-5 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><h4 className="font-display text-[17px] font-extrabold">{concept.title}</h4><Link href={`/aprender/${concept.id}`} className="text-[10.5px] font-bold text-navy underline">Abrir explicação completa</Link></div><p className="mt-3 text-[12.5px] leading-relaxed text-navy/70">{concept.summary}</p><p className="mt-3 border-l-2 border-cyan pl-3 text-[12px] leading-relaxed text-navy/62"><strong>Como explicar:</strong> {concept.howToExplain}</p></article>)}</div></section>
    <ProntidaoDaAula items={support.readiness}/>
  </>;

  const preparar = <>
    <Heading eyebrow="Etapa 2 · Prepare" title="Organize, monte e teste antes da turma chegar" description="Confira quantidades, cuidados, sequência e resultado esperado. Quando houver micro:bit, monte um bloco por vez e teste no simulador antes da placa."/>
    <section className="mt-6 grid max-w-[1100px] gap-5 lg:grid-cols-2">
      <div className="rounded-card-sm bg-white p-5 shadow-card"><h3 className="font-display text-[18px] font-extrabold">Materiais, quantidades e cuidados</h3><div className="mt-4 grid gap-4">{support.materials.map((item) => <div key={item.name} className="grid grid-cols-[42px_1fr] gap-3 border-b border-navy/8 pb-4 last:border-0 last:pb-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan/10 text-cyan"><Wrench size={18}/></span><div><p className="text-[13px] font-bold">{item.name}</p><p className="mt-1 text-[11.5px] text-navy/55">{item.quantity}</p><p className="mt-2 text-[12px] leading-relaxed text-navy/68">{item.use}</p><p className="mt-2 text-[11.5px] leading-relaxed text-coral"><strong>Cuidado:</strong> {item.caution}</p></div></div>)}</div></div>
      <div className="rounded-card-sm border border-amber/20 bg-amber/8 p-5"><h3 className="font-display text-[18px] font-extrabold">Checklist antes da aula</h3><ol className="mt-4 grid gap-2.5">{support.preparation.map((item, index) => <li key={item} className="grid grid-cols-[25px_1fr] gap-2 text-[12.5px] leading-relaxed text-navy/70"><span className="font-mono font-bold text-amber">{index + 1}.</span>{item}</li>)}</ol></div>
    </section>
    {guide ? <div className="mt-8"><GuiaTecnicoMicrobit guide={{ ...guide, diagnostics: support.diagnostics }} part="build"/></div> : <div className="mt-8 max-w-[1020px] rounded-card border border-green/20 bg-green/8 p-5 sm:p-7"><p className="label-mono text-green">Preparação da experiência</p><h3 className="mt-2 font-display text-[20px] font-extrabold">Esta aula não exige programação na placa</h3><p className="mt-3 text-[13px] leading-relaxed text-navy/68">Realize uma rodada completa como participante, prepare um exemplo correto e introduza um erro que possa ser localizado. Deixe visíveis as regras, o objetivo e o critério de conclusão.</p><div className="mt-5 rounded-card-sm bg-white p-4"><p className="text-[13px] font-bold">Resultado que deve estar pronto para demonstrar</p><p className="mt-2 text-[12.5px] leading-relaxed text-navy/68">{plan.test}</p></div></div>}
    <section className="mt-7 max-w-[1020px] rounded-card-sm border border-amber/20 bg-amber/8 p-5"><h3 className="font-display text-[18px] font-extrabold">Ensaio obrigatório do professor</h3><ul className="mt-4 grid gap-3">{support.rehearsal.map((item) => <li key={item} className="flex gap-2 text-[12.5px] leading-relaxed text-navy/70"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-amber"/>{item}</li>)}</ul></section>
  </>;

  const aplicar = <>
    <Heading eyebrow="Etapa 3 · Aplique" title="Conduza a aula minuto a minuto" description="Cada linha separa o que o professor faz, o que os alunos fazem e qual evidência observar. Isso evita transformar a aula em demonstração ou cópia de blocos."/>
    <section className="mt-6 max-w-[1150px] overflow-x-auto rounded-card-sm border border-navy/10 bg-white shadow-card"><table className="w-full min-w-[930px] border-collapse text-left text-[12px]"><thead className="bg-navy text-white"><tr><th className="p-3">Tempo</th><th className="p-3">Fase</th><th className="p-3">O professor faz</th><th className="p-3">Os alunos fazem</th><th className="p-3">Evidência esperada</th></tr></thead><tbody>{support.timeline.map((row) => <tr key={row.title} className="border-b border-navy/8 align-top"><td className="p-3 font-mono font-bold text-cyan">{row.time}</td><td className="p-3 font-bold">{row.title}</td><td className="p-3 leading-relaxed text-navy/70">{row.teacher}</td><td className="p-3 leading-relaxed text-navy/70">{row.students}</td><td className="p-3 leading-relaxed text-navy/70">{row.evidence}</td></tr>)}</tbody></table></section>
    <section className="mt-7 grid max-w-[1100px] gap-5 lg:grid-cols-2"><div className="rounded-card-sm border border-amber/20 bg-amber/8 p-5"><h3 className="font-display text-[18px] font-extrabold">Falas sugeridas</h3><ul className="mt-4 grid gap-3">{support.teacherTalk.map((item) => <li key={item} className="border-l-2 border-amber pl-3 text-[12.5px] italic leading-relaxed text-navy/68">“{item.replace(/^“|”$/g, "") }”</li>)}</ul></div><div className="rounded-card-sm border border-cyan/20 bg-cyan/7 p-5"><h3 className="font-display text-[18px] font-extrabold">Perguntas e respostas esperadas</h3><div className="mt-4 grid gap-3">{support.questions.map((item) => <details key={item.question} className="rounded bg-white p-3"><summary className="cursor-pointer text-[12.5px] font-bold leading-relaxed">{item.question}</summary><p className="mt-2 border-l-2 border-cyan pl-3 text-[12px] leading-relaxed text-navy/65">{item.answer}</p></details>)}</div></div></section>
    <section className="mt-7 max-w-[1100px]"><h3 className="font-display text-[20px] font-extrabold">Adaptações sem improviso</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{support.adaptations.map((item) => <article key={item.title} className="rounded-card-sm border border-navy/8 bg-white p-4 shadow-card"><p className="text-[13px] font-bold">{item.title}</p><p className="mt-2 text-[12px] leading-relaxed text-navy/65">{item.text}</p></article>)}</div></section>
  </>;

  const avaliar = <>
    <Heading eyebrow="Etapa 4 · Avalie" title="Observe a aprendizagem e diagnostique cada erro" description="A aula termina quando o aluno consegue explicar, testar e corrigir — não apenas quando o produto final funciona."/>
    {guide ? <GuiaTecnicoMicrobit guide={{ ...guide, diagnostics: support.diagnostics }} part="evaluate"/> : <section className="mt-6 max-w-[1120px] rounded-card-sm border border-coral/20 bg-white p-5 shadow-card"><div className="flex items-center gap-3"><TriangleAlert className="text-coral"/><h3 className="font-display text-[18px] font-extrabold">Diagnóstico específico desta atividade</h3></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left text-[12px]"><thead><tr className="border-b border-navy/15"><th className="p-2">Problema</th><th className="p-2">Causa provável</th><th className="p-2">Como verificar</th><th className="p-2">Como corrigir</th></tr></thead><tbody>{support.diagnostics.map((item) => <tr key={item.symptom} className="border-b border-navy/8 align-top"><td className="p-2 font-bold">{item.symptom}</td><td className="p-2 leading-relaxed text-navy/65">{item.cause}</td><td className="p-2 leading-relaxed text-navy/65">{item.check}</td><td className="p-2 leading-relaxed text-navy/65">{item.fix}</td></tr>)}</tbody></table></div></section>}
    <section className="mt-7 max-w-[1120px] rounded-card-sm bg-navy p-5 text-white"><div className="flex items-center gap-3"><Sparkles className="text-cyan"/><h3 className="font-display text-[20px] font-extrabold text-white">Rubrica de avaliação</h3></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left text-[12px]"><thead><tr className="border-b border-white/15"><th className="p-2">Critério</th><th className="p-2">Iniciando</th><th className="p-2">Em desenvolvimento</th><th className="p-2">Alcançou</th></tr></thead><tbody>{support.rubric.map((row) => <tr key={row.criterion} className="border-b border-white/10 align-top"><td className="p-2 font-bold text-cyan">{row.criterion}</td><td className="p-2 leading-relaxed text-white/60">{row.beginning}</td><td className="p-2 leading-relaxed text-white/70">{row.developing}</td><td className="p-2 leading-relaxed text-white/80">{row.achieved}</td></tr>)}</tbody></table></div></section>
    <section className="mt-7 grid max-w-[1120px] gap-5 lg:grid-cols-2"><div className="rounded-card-sm border border-purple/20 bg-purple/7 p-5"><h3 className="font-display text-[18px] font-extrabold">Ficha do aluno</h3><ol className="mt-4 grid gap-3">{support.studentSheet.map((item, index) => <li key={item} className="grid grid-cols-[24px_1fr] gap-2 text-[12.5px] leading-relaxed"><span className="font-mono font-bold text-purple">{index + 1}.</span>{item}</li>)}</ol></div><div className="rounded-card-sm border border-cyan/20 bg-cyan/7 p-5"><h3 className="font-display text-[18px] font-extrabold">Evidências de aprendizagem</h3><ul className="mt-4 grid gap-3">{plan.assessment.map((item) => <li key={item} className="border-l-2 border-cyan pl-3 text-[13px] leading-relaxed text-navy/72">{item}</li>)}</ul></div></section>
    <section className="mt-7 max-w-[920px] no-print"><p className="label-mono text-navy/55">Depois desta aula</p><ul className="mt-3 grid gap-2">{[plan.continuity, ...plan.relatedContent].map((ref) => <li key={ref.href + ref.label}><Link href={ref.href} className="text-[13.5px] text-navy underline">{ref.label}</Link></li>)}</ul></section>
    <nav className="mt-8 flex max-w-[1120px] flex-wrap gap-3 border-t border-navy/10 pt-7 no-print">{path?.previous ? <Button href={`/planejar/${path.previous.id}`} variant="secondary">Anterior: {path.previous.title}</Button> : null}{path?.next ? <Button href={`/planejar/${path.next.id}`}>Próxima: {path.next.title}</Button> : <Button href="/aulas">Escolher outra aula</Button>}<Button href="/aulas/caminho" variant="secondary">Ver caminho completo</Button></nav>
  </>;

  return <article className="mx-auto max-w-[1400px] px-5 py-12"><header><div className="flex flex-wrap items-center gap-2"><span className="label-mono text-purple">Plano completo · padrão do portal</span><span className="rounded-pill bg-cyan/10 px-2.5 py-1 font-mono text-[9px] font-bold uppercase tracking-label text-cyan">Aprenda → Prepare → Aplique → Avalie</span></div><h1 className="mt-3 max-w-[24ch] font-display text-[clamp(2rem,4.6vw,3.2rem)] leading-none tracking-display">{plan.title}</h1><p className="mt-4 max-w-[65ch] text-[15px] leading-relaxed text-navy/80">{support.promise}</p><p className="mt-4 max-w-[70ch] border-l-2 border-cyan pl-3 text-[13px] leading-relaxed text-navy/65"><strong>Aplicação real:</strong> {support.everyday}</p><p className="mt-4 text-[13px] text-navy/70"><strong>{plan.duration} minutos</strong> · {years} · {NOMES_DAS_TURMAS[plan.classSize]} · {NOMES_DOS_NIVEIS_DE_PLANO[plan.level]}</p><div className="mt-6 flex flex-wrap items-center gap-3 no-print"><BotaoImprimir/><BotaoFavorito kind="plano" id={plan.id}/><Button href="/planejar" variant="secondary">Encontrar outra aula</Button><MarcarLido id={`planejar:${plan.id}`} rotulo="Aula concluída"/></div>{path ? <p className="mt-4 label-mono text-purple">Aula {path.position} de {total} no caminho recomendado</p> : null}</header><EtapasGuiadas aprender={aprender} preparar={preparar} aplicar={aplicar} avaliar={avaliar}/></article>;
}
