import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowRight, BookOpenCheck, CheckCircle2, ExternalLink, Lightbulb, Wrench } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { BRAND } from "@/config/brand";
import { LESSON_PLANS } from "@/data/lessonPlans";
import { CapaDaAula } from "@/components/planner/CapaDaAula";
import { MAKECODE_CATEGORIES, makeCodeCategoryById } from "@/data/makecodeCatalog";
import { MICROBIT_TECHNICAL_GUIDES } from "@/data/microbitTechnicalGuides";

export function generateStaticParams() { return MAKECODE_CATEGORIES.map((category) => ({ id: category.id })); }
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const category = makeCodeCategoryById(id);
  if (!category) return { title: `Categoria não encontrada — ${BRAND.name}` };
  return { title: `${category.title} no MakeCode — ${BRAND.name}`, description: category.summary };
}

type Starter = { challenge: string; blocks: string[]; expected: string; test: string; answer: string };
const starter = (challenge: string, blocks: string[], expected: string, test: string, answer: string): Starter => ({ challenge, blocks, expected, test, answer });
const STARTERS: Record<string, Starter> = {
  basico: starter("Crie uma saudação que aparece uma vez e depois pisca um coração.", ["Básico → ao iniciar", "mostrar texto OI", "mostrar ícone coração", "pausa 500 ms", "limpar tela"], "A placa rola OI, mostra o coração por meio segundo e apaga.", "Reinicie duas vezes e confira a mesma ordem.", "Ao iniciar executa uma vez; a pausa permite ver o ícone antes de limpar."),
  entrada: starter("Faça A mostrar feliz e agitar lançar um dado.", ["Entrada → no botão A pressionado", "Básico → mostrar ícone feliz", "Entrada → ao agitar", "Básico → mostrar número", "Matemática → aleatório 1 a 6"], "A mostra feliz; cada agitada mostra 1 a 6.", "Teste cada entrada separadamente.", "São dois eventos independentes, esperando entradas diferentes."),
  musica: starter("Crie uma campainha de três notas no botão A.", ["Entrada → no botão A", "Música → volume 128", "tocar Dó por 1 batida", "tocar Mi por 1 batida", "tocar Sol por 2 batidas"], "Três notas; a última dura o dobro.", "Mude o andamento sem mudar notas.", "Batida controla duração relativa; andamento controla velocidade geral."),
  led: starter("Desenhe uma diagonal usando coordenadas.", ["Básico → ao iniciar", "Laços → índice de 0 até 4", "LED → plotar x índice y índice", "pausa 200 ms"], "Cinco pontos formam uma diagonal.", "Troque y por 4 − índice.", "As coordenadas válidas são de 0 a 4."),
  radio: starter("Envie um voto com A e mostre o recebido.", ["Ao iniciar → rádio grupo 7", "No botão A → enviar número 1", "Ao receber número recebido", "mostrar número recebido"], "A em uma placa faz as placas do grupo 7 mostrarem 1.", "Mude uma placa para grupo 8.", "Emissor e receptor precisam usar o mesmo grupo e tipo de mensagem."),
  repeticoes: starter("Faça um coração piscar exatamente quatro vezes.", ["ao iniciar", "repetir 4 vezes", "mostrar coração", "pausa 300 ms", "limpar tela", "pausa 300 ms"], "Quatro piscadas completas.", "Mova limpar tela para fora e compare.", "Tudo que repete precisa ficar dentro do laço."),
  logica: starter("Mostre sol se luz > 100; senão, lua.", ["para sempre", "se/senão", "nível de luz > 100", "mostrar sol", "senão → mostrar lua"], "O ícone muda ao cruzar o limite.", "Cubra a matriz e calibre o limite.", "A condição é revista porque está em para sempre."),
  variaveis: starter("Crie contador: A soma; B mostra.", ["criar pontos", "ao iniciar → definir pontos 0", "A → alterar pontos por 1", "B → mostrar pontos"], "Cada A soma um; B mostra o total.", "A três vezes e B deve mostrar 3.", "Definir substitui; alterar soma ao valor guardado."),
  matematica: starter("Faça um dado eletrônico de 1 a 6.", ["Entrada → ao agitar", "Básico → mostrar número", "Matemática → aleatório 1 a 6"], "Cada agitada mostra um inteiro de 1 a 6.", "Registre 20 resultados.", "Aleatório não garante equilíbrio em poucas tentativas."),
  funcoes: starter("Crie sinalPositivo e chame em A e B.", ["criar função sinalPositivo", "dentro → mostrar sim", "dentro → tocar som feliz", "A → chamar sinalPositivo", "B → chamar sinalPositivo"], "A e B dão a mesma resposta sem duplicação.", "Mude a função; ambos devem mudar.", "Definir escreve a receita; chamar executa."),
  listas: starter("Guarde três notas e mostre cada uma.", ["definir notas para [3, 5, 7]", "para cada valor de notas", "mostrar número valor", "pausa 300 ms"], "Mostra 3, 5 e 7.", "Adicione 9 ao fim.", "O laço percorre itens; índice direto começa em 0."),
  texto: starter("Monte mensagem com nome e pontuação.", ["definir nome ANA", "definir pontos 4", "mostrar texto", "juntar nome, FEZ e pontos"], "Rola ANA FEZ 4.", "Troque só as variáveis.", "Número é convertido para formar uma cadeia."),
  jogos: starter("Mova um sprite e pontue na borda.", ["criar jogador x2 y2", "A → jogador mover 1", "se tocando borda", "adicionar 1 ponto", "jogador quicar"], "O ponto anda, pontua e rebate.", "Conte três colisões.", "Guarde o sprite numa variável para usá-lo depois."),
  imagens: starter("Crie imagem larga e faça rolar.", ["ao iniciar", "criar imagem grande com seta", "rolar 1 pixel a cada 200 ms"], "A faixa atravessa a matriz.", "Compare 50 e 500 ms.", "O intervalo controla velocidade e legibilidade."),
  pinos: starter("Leia potenciômetro P0 e mostre barra.", ["ligar extremos em 3V/GND e centro em P0", "para sempre", "leitura analógica P0", "plotar gráfico até 1023", "pausa 100 ms"], "A barra varia de 0 a 25 LEDs.", "Revise 3V, GND e sinal com placa desligada.", "Analógico vai de 0 a 1023 e precisa de GND comum."),
  serial: starter("Envie luz ao console.", ["para sempre", "serial escrever valor luz", "valor → nível de luz", "pausa 200 ms"], "Console mostra série luz.", "Cubra a matriz e observe queda.", "A pausa controla a taxa e evita congestionamento."),
  controle: starter("Anime e toque som em paralelo.", ["ao iniciar", "executar em paralelo → melodia", "fluxo principal → repetir animação", "mostrar ícone sim"], "Som e imagem avançam juntos.", "Remova paralelo e compare.", "Evite duas tarefas alterando o mesmo recurso sem regra."),
  bluetooth: starter("Publique botões e LED para um app.", ["iniciar serviço de botão", "iniciar serviço LED", "ao conectar → mostrar sim", "ao desconectar → mostrar não"], "App emparelhado lê botões e controla matriz.", "Cheque pareamento, conexão e permissões.", "Parear cria confiança; conectar abre a sessão. Rádio fica indisponível."),
  extensoes: starter("Valide uma extensão pelo exemplo mínimo.", ["pesquisar nome exato do fabricante", "revisar compatibilidade", "adicionar extensão", "abrir exemplo mínimo", "testar uma entrada/saída"], "Nova categoria aparece e exemplo funciona.", "Confira modelo, porta, energia e versão.", "O catálogo é aberto; cada kit exige documentação própria."),
};

export default async function MakeCodeCategoryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const category = makeCodeCategoryById(id); if (!category) notFound();
  const workshop = STARTERS[category.id];
  const categoryNames: Record<string, string[]> = {
    basico: ["Básico"], entrada: ["Entrada"], musica: ["Música"], led: ["LED"], radio: ["Rádio"], repeticoes: ["Ciclos"], logica: ["Lógica"], variaveis: ["Variáveis"], matematica: ["Matemática"], funcoes: ["Funções"], listas: ["Matrizes"], texto: ["Texto"], jogos: ["Jogo"], imagens: ["Imagens"], pinos: ["Pinos", "Servo"], serial: ["Serial", "Data Logger"], controle: ["Controle"], bluetooth: ["Bluetooth"], extensoes: ["Extensões", "IA gerada"],
  };
  const relatedIds = MICROBIT_TECHNICAL_GUIDES.filter((guide) => guide.blocks.some((block) => (categoryNames[category.id] ?? []).includes(block.category))).map((guide) => guide.id);
  const lessons = [...new Set([...category.lessonIds, ...relatedIds])].map((id) => LESSON_PLANS.find((lesson) => lesson.id === id)).filter(Boolean).slice(0, 12);
  const previous = MAKECODE_CATEGORIES[category.order - 2]; const next = MAKECODE_CATEGORIES[category.order];
  return <article className="mx-auto max-w-[1400px] px-5 py-12 md:px-8">
    <header className="max-w-[920px]"><p className="label-mono text-cyan">Aula {String(category.order).padStart(2, "0")} de {MAKECODE_CATEGORIES.length} · {category.menu}</p><h1 className="mt-3 font-display text-[clamp(2.1rem,5vw,3.8rem)] leading-none tracking-display">{category.title}</h1><p className="mt-4 max-w-[70ch] text-[15px] leading-relaxed text-navy/72">{category.summary}</p><div className="mt-5 flex flex-wrap gap-2 text-[11px] font-bold"><span className="rounded-pill bg-cyan/12 px-3 py-2">{category.level}</span><span className="rounded-pill bg-navy/6 px-3 py-2">{category.version}</span><span className="rounded-pill bg-purple/10 px-3 py-2">{category.families.length} famílias explicadas</span></div></header>
    <section className="mt-10 grid gap-4 lg:grid-cols-[.75fr_1.25fr]"><Card realce="amber"><Lightbulb className="text-amber"/><h2 className="mt-3 text-[20px]">Como pensar</h2><p className="mt-2 text-[14px] leading-relaxed text-navy/70">{category.mentalModel}</p></Card><Card realce="cyan"><BookOpenCheck className="text-cyan"/><h2 className="mt-3 text-[20px]">Objetivo do professor</h2><p className="mt-2 text-[14px] leading-relaxed text-navy/70">Localizar a categoria, explicar cada família, prever o resultado e diagnosticar o erro mais comum sem apagar o trabalho do aluno.</p></Card></section>
    <section className="mt-14"><p className="label-mono text-purple">Referência completa em linguagem simples</p><h2 className="mt-2 text-[28px]">Tudo que esta categoria faz</h2><p className="mt-2 max-w-[72ch] text-[13.5px] leading-relaxed text-navy/65">Cada cartão representa uma família. Pino, gesto, direção, unidade e outras opções aparecem dentro do bloco em menus.</p><div className="mt-6 grid gap-4 xl:grid-cols-2">{category.families.map((family, index) => <Card key={family.name} className="p-5"><p className="label-mono text-cyan">{String(index + 1).padStart(2, "0")} · bloco/família</p><h3 className="mt-2 text-[18px]">{family.name}</h3><dl className="mt-4 grid gap-3 text-[12.5px] leading-relaxed"><div><dt className="font-bold">O que faz</dt><dd className="text-navy/68">{family.does}</dd></div><div><dt className="font-bold">Quando usar</dt><dd className="text-navy/68">{family.use}</dd></div><div><dt className="font-bold text-green">Resultado esperado</dt><dd className="text-navy/68">{family.result}</dd></div><div><dt className="font-bold text-coral">Erro provável</dt><dd className="text-navy/68">{family.error}</dd></div></dl></Card>)}</div></section>
    <section className="mt-14 rounded-card bg-navy p-6 text-white md:p-8"><p className="label-mono text-cyan">Oficina guiada · 50 minutos</p><h2 className="mt-2 text-[28px] text-white">{workshop.challenge}</h2><div className="mt-7 grid gap-6 lg:grid-cols-2"><div><h3 className="text-[16px] text-white">Blocos e ligações na ordem</h3><ol className="mt-4 grid gap-2">{workshop.blocks.map((block, index) => <li key={block} className="flex gap-3 rounded-card-sm bg-white/8 p-3 text-[12.5px]"><span className="font-mono font-bold text-cyan">{index + 1}</span><span>{block}</span></li>)}</ol></div><div className="grid content-start gap-4"><div className="rounded-card-sm bg-green/12 p-4"><p className="label-mono text-green">Resultado esperado</p><p className="mt-2 text-[13px] text-white/78">{workshop.expected}</p></div><div className="rounded-card-sm bg-cyan/10 p-4"><p className="label-mono text-cyan">Como testar</p><p className="mt-2 text-[13px] text-white/78">{workshop.test}</p></div><div className="rounded-card-sm bg-amber/10 p-4"><p className="label-mono text-amber">Resposta esperada</p><p className="mt-2 text-[13px] text-white/78">{workshop.answer}</p></div></div></div><ol className="mt-8 grid gap-3 md:grid-cols-5">{[["0–5", "Mostre o desafio"], ["5–15", "Localize os blocos"], ["15–30", "Monte e simule"], ["30–40", "Mude e depure"], ["40–50", "Explique e registre"]].map(([time, action]) => <li key={time} className="rounded-card-sm border border-white/12 p-3"><strong className="text-cyan">{time} min</strong><p className="mt-1 text-[11.5px] text-white/65">{action}</p></li>)}</ol></section>
    <section className="mt-14"><p className="label-mono text-coral">Diagnóstico técnico</p><h2 className="mt-2 text-[28px]">Se não funcionar, não recomece</h2><div className="mt-5 grid gap-3 md:grid-cols-3"><Card><AlertTriangle className="text-coral"/><h3 className="mt-3 text-[16px]">1. Entrada</h3><p className="mt-2 text-[12.5px] text-navy/65">O evento disparou? Provoque exatamente a entrada escolhida.</p></Card><Card><Wrench className="text-amber"/><h3 className="mt-3 text-[16px]">2. Lógica</h3><p className="mt-2 text-[12.5px] text-navy/65">Leia de cima para baixo e altere uma coisa por vez.</p></Card><Card><CheckCircle2 className="text-green"/><h3 className="mt-3 text-[16px]">3. Placa</h3><p className="mt-2 text-[12.5px] text-navy/65">Confira V1/V2, download, energia, GND e ligação.</p></Card></div></section>
    <section className="mt-14"><p className="label-mono text-green">Aulas que aplicam isto</p><h2 className="mt-2 text-[28px]">Do conceito para a sala</h2><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{lessons.map((lesson) => lesson ? <Card key={lesson.id} className="group flex flex-col p-0"><CapaDaAula lesson={lesson}/><div className="flex flex-1 flex-col p-5"><h3 className="text-[17px]">{lesson.title}</h3><p className="mt-2 text-[12.5px] text-navy/65">{lesson.objective}</p><Button href={`/planejar/${lesson.id}`} variant="secondary" className="mt-5">Abrir aula detalhada</Button></div></Card> : null)}</div><div className="mt-5 rounded-card-sm bg-amber/10 p-4"><p className="text-[13px]"><strong>Outras criações:</strong> {category.projects.join(" · ")}</p></div></section>
    <section className="mt-14 flex flex-wrap gap-3 border-t border-navy/10 pt-8">{previous ? <Button href={`/makecode/${previous.id}`} variant="secondary">Anterior: {previous.menu}</Button> : null}{next ? <Button href={`/makecode/${next.id}`}>Próxima: {next.menu} <ArrowRight size={14}/></Button> : <Button href="/planejar">Ir para todas as aulas</Button>}<a href={category.source} target="_blank" rel="noreferrer" className="inline-flex min-h-[42px] items-center gap-2 rounded-pill px-4 text-[12px] font-bold text-cyan">Referência oficial <ExternalLink size={14}/></a></section>
  </article>;
}
